title: UC Love Data Week
description: > # this means to ignore newlines until "baseurl:"
  UC Love Data Week is a week-long offering of presentations and workshops focused on data access, management, security, sharing, and preservation
baseurl: "" # the subpath of your site, e.g. /blog
url: "uc-love-data-week.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

logo: "../assets/img/ldw-circuit-light-transparent.png"

social:
  name: Slack
  link: "https://uclovedataweek.slack.com/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2021_pages', '_2022_pages', '_2023_pages', '_2024_pages', '_2025_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: slack
    url: https://uclovedataweek.slack.com/

# Build settings
markdown: kramdown
permalink: pretty
